# Generated by Django 2.1.7 on 2019-04-23 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=3)),
                ('sazonalidade', models.CharField(max_length=45)),
                ('data_pagamento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf_cnpj', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('assinaturas', models.ManyToManyField(to='app_base.Assinatura')),
            ],
        ),
        migrations.CreateModel(
            name='Cooperativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('aprovado', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=80)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=80)),
                ('telefone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=3)),
                ('quantidade', models.IntegerField()),
                ('cooperativa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app_base.Cooperativa')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('tipo', models.CharField(max_length=25)),
                ('un_medida', models.CharField(max_length=2)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img_produtos')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='producao',
            name='produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app_base.Produto'),
        ),
        migrations.AddField(
            model_name='pacote',
            name='produtos',
            field=models.ManyToManyField(to='app_base.Produto'),
        ),
        migrations.AddField(
            model_name='cooperativa',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_base.Endereco'),
        ),
        migrations.AddField(
            model_name='cooperativa',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_base.Endereco'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='pacotes',
            field=models.ManyToManyField(to='app_base.Pacote'),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='tipo_pagamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app_base.TipoPagamento'),
        ),
    ]
