# Generated by Django 2.1.7 on 2019-05-01 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cooperativa',
            old_name='user',
            new_name='usuario',
        ),
    ]
