# Generated by Django 2.1.7 on 2019-05-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0003_auto_20190430_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='nome',
            field=models.CharField(default='', max_length=120),
        ),
    ]
