# Generated by Django 2.1.7 on 2019-05-02 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0004_assinatura_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinatura',
            name='data_pagamento',
        ),
    ]
