# Generated by Django 2.1.7 on 2019-05-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0006_auto_20190501_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinatura',
            name='tipo_pagamento',
        ),
        migrations.AddField(
            model_name='assinatura',
            name='tipo_pagamento',
            field=models.ManyToManyField(to='app_base.TipoPagamento'),
        ),
    ]
