# Generated by Django 2.1.7 on 2019-05-02 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0007_auto_20190502_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacote',
            name='produtos',
        ),
        migrations.RemoveField(
            model_name='assinatura',
            name='pacotes',
        ),
        migrations.AddField(
            model_name='assinatura',
            name='producoes',
            field=models.ManyToManyField(blank=True, to='app_base.Producao'),
        ),
        migrations.AlterField(
            model_name='cooperativa',
            name='usuario',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Pacote',
        ),
    ]
