# Generated by Django 2.1.7 on 2019-05-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0008_auto_20190502_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativa',
            name='assinaturas',
            field=models.ManyToManyField(blank=True, to='app_base.Assinatura'),
        ),
        migrations.AlterField(
            model_name='assinatura',
            name='producoes',
            field=models.ManyToManyField(to='app_base.Producao'),
        ),
    ]
