# Generated by Django 2.1.7 on 2019-05-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0009_auto_20190502_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(default='padrao', max_length=80),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='logradouro',
            field=models.CharField(max_length=130),
        ),
    ]
