# Generated by Django 2.1.7 on 2019-05-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0010_auto_20190503_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativa',
            name='cnpj',
            field=models.CharField(default='123', max_length=20),
        ),
    ]
