# Generated by Django 2.1.7 on 2019-05-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0011_cooperativa_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativa',
            name='email',
            field=models.EmailField(default='ads@gmail.com', max_length=254),
        ),
    ]
