# Generated by Django 2.1.7 on 2019-05-12 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0013_auto_20190512_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telefone',
            old_name='telefone',
            new_name='numero',
        ),
    ]
