# Generated by Django 2.1.7 on 2019-05-12 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0014_auto_20190512_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telefone',
            old_name='numero',
            new_name='telefone',
        ),
    ]
