# Generated by Django 2.1.7 on 2019-05-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0017_auto_20190512_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativa',
            name='assinaturas',
            field=models.ManyToManyField(blank=True, null=True, to='app_base.Assinatura'),
        ),
    ]
