# Generated by Django 2.1.7 on 2019-05-13 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0018_auto_20190512_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producao',
            name='cooperativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_base.Cooperativa'),
        ),
    ]
