# Generated by Django 2.1.7 on 2019-05-13 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0019_auto_20190513_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativa',
            name='assinaturas',
            field=models.ManyToManyField(blank=True, to='app_base.Assinatura'),
        ),
        migrations.AlterField(
            model_name='producao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_base.Produto'),
        ),
    ]
