# Generated by Django 2.1.7 on 2019-05-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0020_auto_20190513_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='producoes',
            field=models.ManyToManyField(related_name='assinatura', to='app_base.Producao'),
        ),
    ]
