# Generated by Django 2.1.7 on 2019-05-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0021_auto_20190514_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='producoes',
            field=models.ManyToManyField(to='app_base.Producao'),
        ),
    ]
