# Generated by Django 2.1.7 on 2019-05-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0022_auto_20190514_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='producoes',
            field=models.ManyToManyField(related_name='producao', to='app_base.Producao'),
        ),
    ]
